# Use typescript-eslint to lint our TypeScript code
parser: "@typescript-eslint/parser"

# Use Airbnb rules to check code
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended

plugins:
  - import

# TypeScript compatibility
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript: {}

# Additional rules
rules:
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/no-explicit-any": error
  multiline-comment-style: error

  # Re-adding changed Airbnb rules (removed most likely from eslint/recommended)
  "@typescript-eslint/camelcase":
    - error
    - properties: never

  "@typescript-eslint/indent":
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: 1
      outerIIFEBody: 1
      FunctionDeclaration:
        parameters: 1
        body: 1
      FunctionExpression:
        parameters: 1
        body: 1
      CallExpression:
        arguments: 1
      ArrayExpression: 1
      ObjectExpression: 1
      ImportDeclaration: 1
      flatTernaryExpressions: false
      ignoreComments: false


  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
