extends:
  - airbnb-base

rules:
  linebreak-style: off

  import/order:
    - error
    - groups:
      - [builtin, external, internal]
      - [sibling, parent, index]
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: false
