# Use typescript-eslint to lint our TypeScript code
parser: "@typescript-eslint/parser"

# Use Airbnb rules to check code
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended

plugins:
  - import

# TypeScript compatibility
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript: {}

# Additional rules
rules:
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/no-explicit-any": error
  multiline-comment-style: error

  # Re-adding removed Airbnb rules (removed most likely from eslint/recommended)
  max-len:
    - error
    - code: 100
  no-console: error
  prefer-destructuring: error
